name: pesona2
description: "final project for thesis"

publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  #  Package
  #--------------------------------------------------------
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  crypto: ^3.0.3
  http: ^1.2.1
  carousel_slider: ^4.2.1
  custom_accordion: ^1.0.0
  custom_line_indicator_bottom_navbar: ^0.0.8
  flutter_neat_and_clean_calendar: ^0.3.0
  table_calendar: ^3.0.9
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_database: ^10.5.7
  internet_connection_checker_plus: ^2.4.2
  connectivity_plus: ^6.0.3
  flutter_profile_picture: ^2.0.0
  email_validator: ^2.1.17
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2
  get: ^4.6.6
  flutter_html: ^3.0.0-beta.2
  intl: ^0.19.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.1+1
#--------------------------------------------------------


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
