// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOENDDvswbm3nh2vg7cu_2e0VCWKHVF7w',
    appId: '1:611611743289:web:7ec3540628c66632a229e8',
    messagingSenderId: '611611743289',
    projectId: 'admin-persona-2ddcc',
    authDomain: 'admin-persona-2ddcc.firebaseapp.com',
    databaseURL: 'https://admin-persona-2ddcc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-persona-2ddcc.appspot.com',
    measurementId: 'G-VDLXSCW49M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmt2TD_05aWM1X5XDL_M_3x8eLz82l2CA',
    appId: '1:611611743289:android:ed757ab05f3f7e7ba229e8',
    messagingSenderId: '611611743289',
    projectId: 'admin-persona-2ddcc',
    databaseURL: 'https://admin-persona-2ddcc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-persona-2ddcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1IrFILcvAUIFWrkHC3jJdMSw5QoLHwck',
    appId: '1:611611743289:ios:6102494b294f8f44a229e8',
    messagingSenderId: '611611743289',
    projectId: 'admin-persona-2ddcc',
    databaseURL: 'https://admin-persona-2ddcc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-persona-2ddcc.appspot.com',
    iosBundleId: 'com.example.pesona2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1IrFILcvAUIFWrkHC3jJdMSw5QoLHwck',
    appId: '1:611611743289:ios:6102494b294f8f44a229e8',
    messagingSenderId: '611611743289',
    projectId: 'admin-persona-2ddcc',
    databaseURL: 'https://admin-persona-2ddcc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-persona-2ddcc.appspot.com',
    iosBundleId: 'com.example.pesona2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOENDDvswbm3nh2vg7cu_2e0VCWKHVF7w',
    appId: '1:611611743289:web:4649e3f27cf5f5baa229e8',
    messagingSenderId: '611611743289',
    projectId: 'admin-persona-2ddcc',
    authDomain: 'admin-persona-2ddcc.firebaseapp.com',
    databaseURL: 'https://admin-persona-2ddcc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-persona-2ddcc.appspot.com',
    measurementId: 'G-P0C08SJJ95',
  );
}
